name: 'snowplow_identities_integration_tests'
version: '0.0.1'
config-version: 2

profile: 'integration_tests'

dispatch:
  - macro_namespace: dbt
    search_order: ['snowplow_utils', 'dbt']

model-paths:
  - models
test-paths:
  - tests
seed-paths:
  - data
macro-paths:
  - macros
clean-targets:
  - target
  - dbt_modules
  - dbt_packages

quoting:
  identifier: false
  schema: false

models:
  snowplow_identities_integration_tests:
    +schema: "snplw_identities_int_tests"
    +bind: false
    source:
      snowflake:
        +enabled: "{{ target.type == 'snowflake' | as_bool() }}"
      bigquery:
        +enabled: "{{ target.type == 'bigquery' | as_bool() }}"
    actual:
      +materialized: table
    expected:
      +materialized: table

vars:
  test_group: "basic"
  snowplow_identities:
    snowplow__atomic_schema: "{{ target.schema ~ '_snplw_identities_int_tests' }}"
    snowplow__events_table: "{{ var('test_group', 'basic') ~ '_events_stg' }}"
    snowplow__start_date: '2026-03-01'
    snowplow__backfill_limit_days: 30
    snowplow__license_accepted: true
    snowplow__app_id: []
    snowplow__allow_null_dvce_tstamps: true

seeds:
  snowplow_identities_integration_tests:
    +schema: "snplw_identities_int_tests"
    +quote_columns: false
    source:
      +column_types:
        event_id: "{{ 'string' if target.type in ['bigquery'] else 'varchar' }}"
        event_name: "{{ 'string' if target.type in ['bigquery'] else 'varchar' }}"
        app_id: "{{ 'string' if target.type in ['bigquery'] else 'varchar' }}"
        collector_tstamp: timestamp
        derived_tstamp: timestamp
        load_tstamp: timestamp
        dvce_created_tstamp: timestamp
        domain_userid: "{{ 'string' if target.type in ['bigquery'] else 'varchar' }}"
        user_id: "{{ 'string' if target.type in ['bigquery'] else 'varchar' }}"
        contexts_com_snowplowanalytics_snowplow_identity_1: "{{ 'string' if target.type in ['bigquery'] else 'varchar(65535)' }}"
        unstruct_event_com_snowplowanalytics_snowplow_identity_merge_1: "{{ 'string' if target.type in ['bigquery'] else 'varchar(65535)' }}"
    expected:
      +column_types:
        snowplow_id: "{{ 'string' if target.type in ['bigquery'] else 'varchar' }}"
        active_snowplow_id: "{{ 'string' if target.type in ['bigquery'] else 'varchar' }}"
        previous_snowplow_id: "{{ 'string' if target.type in ['bigquery'] else 'varchar' }}"
        first_seen_event_id: "{{ 'string' if target.type in ['bigquery'] else 'varchar' }}"
        first_seen_app_id: "{{ 'string' if target.type in ['bigquery'] else 'varchar' }}"
        first_app_id: "{{ 'string' if target.type in ['bigquery'] else 'varchar' }}"
        last_app_id: "{{ 'string' if target.type in ['bigquery'] else 'varchar' }}"
        domain_userid: "{{ 'string' if target.type in ['bigquery'] else 'varchar' }}"
        user_id: "{{ 'string' if target.type in ['bigquery'] else 'varchar' }}"
        id_type: "{{ 'string' if target.type in ['bigquery'] else 'varchar' }}"
        id_value: "{{ 'string' if target.type in ['bigquery'] else 'varchar' }}"
        change_type: "{{ 'string' if target.type in ['bigquery'] else 'varchar' }}"
        created_at: timestamp
        merged_at: timestamp
        effective_at: timestamp
        superseded_at: timestamp
        first_derived_tstamp: timestamp
        last_derived_tstamp: timestamp
        first_seen_at: timestamp
        last_seen_at: timestamp
        is_current: boolean

flags:
  require_generic_test_arguments_property: true
